logging:
  level:
    root: info
spring:
  application:
    name: test-live-secrets-k8s
  cloud:
    kubernetes:
      config:
        name: test-live-secrets-k8s-config
      secrets:
        enabled: true
        enable-api: true
        name: test-live-secrets-k8s-secrets

management:
  endpoints:
    web:
      exposure:
        include: "*"

test-live-secrets-k8s:
  test-configmap-property: test-configmap-value
  test-secret-property: test-secret-value
  test-mounted-secret-property: test-mounted-secret-value