apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "test-live-secrets-k8s.fullname" . }}
  labels:
    {{- include "test-live-secrets-k8s.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "test-live-secrets-k8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      labels:
        {{- include "test-live-secrets-k8s.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Chart.Name }}-serviceaccount
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
          startupProbe:
            failureThreshold: 90
            httpGet:
              path: /actuator/health/liveness
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: SPRING_CONFIG_IMPORT
              value: "kubernetes:"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"