apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}-rolebinding
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ .Chart.Name }}-role
subjects:
  - kind: ServiceAccount
    name: {{ .Chart.Name }}-serviceaccount
    namespace: {{ .Release.Namespace }}