apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
  labels:
    spring.cloud.kubernetes.config.informer.enabled: 'true'
type: Opaque
data:
  test-live-secrets-k8s.test-secret-property: {{ .Values.secrets.someSecret | b64enc }}
  test-live-secrets-k8s.test-mounted-secret-property: {{ .Values.secrets.someSecret | b64enc }}